name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
  GH_USERNAME: "tlienart"
  REPO_PREFIX: "Xranklin.jl"
  PREVIEWS_PREFIX: "previews/PR"  # will be followed by PR number

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: üëÄ Set preview path for PRs
        run: |
          if ${{ github.event_name == 'pull_request' }}
          then
            echo 'PRID=${{ env.PREVIEWS_PREFIX}}${{ github.event.number}}' >> $GITHUB_ENV
          else
            echo 'PRID=' >> $GITHUB_ENV
          fi
        shell: bash

      - name: üöÄ Build and Deploy
        uses: tlienart/xranklin-build-action@main
        with:
          SITE_FOLDER: "docs/"
          BASE_URL_PREFIX: ${{ env.REPO_PREFIX }}
          PREVIEW: ${{ env.PRID }}
          PYTHON_LIBS: "matplotlib pandas ansi2html"
          LUNR: true

      - name: üóíÔ∏è Preview URL indication for PRs
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview should be up in a couple of mins at
            https://${{ env.GH_USERNAME }}.github.io/${{ env.REPO_PREFIX }}/${{ env.PRID }}
            (if you get a 404, wait 30s then refresh).
        if: github.event_name == 'pull_request'
