name: PyPlot

on:
  push:
    branches:
      - preview
      - main
      - ttfx

env:
  INDEX: "test/abc_min/index.md"
  SETUP: "using Pkg; Pkg.activate(\"test/abc_min\"); Pkg.add([\"PyCall\", \"PyPlot\"]); Pkg.build(\"PyCall\");"
  BUILD: ""
  PPATH: "Xranklin.jl"
  TARGD: "ttfx/pyplot"
  SITED: "test/abc_min"

jobs:
  pyplot:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # =======================================================================
      # -- deps --
      - name: Install Python ðŸ
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Matplotlib ðŸ
        run: |
             pip install matplotlib
             export PYTHON=$(which python)

      # -- modify index --
      - name: Set index.md ðŸ“–
        run: |
              echo "# TTFX PyPlot"                   > ${{ env.INDEX }}
              echo "\`\`\`!"                        >> ${{ env.INDEX }}
              echo "using Pyplot"                   >> ${{ env.INDEX }}
              echo "x = range(0, pi, length=500)"   >> ${{ env.INDEX }}
              echo "y = @. sin(exp(x)) * sinc(x)"   >> ${{ env.INDEX }}
              echo "figure(figsize=(6, 4))"         >> ${{ env.INDEX }}
              echo "plot(x, y)"                     >> ${{ env.INDEX }}
              echo "gcf()"                          >> ${{ env.INDEX }}
              echo "\`\`\`"                         >> ${{ env.INDEX }}
              cat ${{ env.INDEX }}

      # =======================================================================

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      - name: Building website ðŸš§
        run: ${{ env.BUILD }} julia -e '
                ${{ env.SETUP }};
                Pkg.add(
                  url="https://github.com/tlienart/Xranklin.jl",
                  rev="main"
                  );
                using Xranklin;
                build("${{ env.SITED }}";
                      clear=true,
                      prefix=joinpath(
                        "${{ env.PPATH }}",
                        "${{ env.TARGD }}"
                        )
                      );'

      # Deployment
      - name: No Jekyll
        run: touch ${{ env.SITED }}/__site/.nojekyll
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ env.SITED }}/__site
          TARGET-FOLDER: "${{ env.TARGD }}"
