name: Gadfly

on:
  push:
    branches:
      - ttfx

env:
  INDEX: "test/abc_min/index.md"
  SETUP: "using Pkg; Pkg.add([\"Gadfly\"]);"
  BUILD: ""
  PPATH: "Xranklin.jl"
  TARGD: "ttfx/gadfly"
  SITED: "test/abc_min"
  START: $(date +%s)

jobs:
  gadfly:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # =======================================================================
      # -- modify index --
      - name: Set index.md ðŸ“–
        env:
          START2: $(date +%s)
        run: |
              echo "# TTFX Gadfly"                  > ${{ env.INDEX }}
              echo "\`\`\`!"                       >> ${{ env.INDEX }}
              echo "setgvar!(:skiplatex, true)"    >> ${{ env.INDEX }}
              echo "using Gadfly"                  >> ${{ env.INDEX }}
              echo "x = range(0, pi, length=500)"  >> ${{ env.INDEX }}
              echo "y = @. sin(exp(x)) * sinc(x)"  >> ${{ env.INDEX }}
              echo "plot(x=x, y=y, Geom.path)"     >> ${{ env.INDEX }}
              echo "\`\`\`"                        >> ${{ env.INDEX }}
              echo "# TIME"                                  >> ${{ env.INDEX }}
              echo "\`\`\`!"                                 >> ${{ env.INDEX }}
              echo "using Dates"                             >> ${{ env.INDEX }}
              echo "t0  = datetime2unix(now())"              >> ${{ env.INDEX }}
              echo "delta  = t0 - ${{ env.START  }}"         >> ${{ env.INDEX }}
              echo "delta2 = t0 - ${{ env.START2 }}"         >> ${{ env.INDEX }}
              echo "delta  = round(delta  / 60, digits=2)"   >> ${{ env.INDEX }}
              echo "delta2 = round(delta2, digits=2)"        >> ${{ env.INDEX }}
              echo "ps(s) = joinpath(Utils.path(:site), s)"  >> ${{ env.INDEX }}
              echo "write(ps(\"timer\"), delta)"             >> ${{ env.INDEX }}
              echo "write(ps(\"timer2\"), delta)"            >> ${{ env.INDEX }}
              echo "println(\"Time taken: \$(delta)min.\")"  >> ${{ env.INDEX }}
              echo "println(\"Time taken2: \$(delta2)s.\")"  >> ${{ env.INDEX }}
              echo "\`\`\`"                                  >> ${{ env.INDEX }}
              cat ${{ env.INDEX }}


      # =======================================================================

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      - name: Building website ðŸš§
        run: ${{ env.BUILD }} julia -e '
                ${{ env.SETUP }};
                Pkg.add(
                  url="https://github.com/tlienart/Xranklin.jl",
                  rev="main"
                  );
                using Xranklin;
                build("${{ env.SITED }}";
                      clear=true,
                      prefix=joinpath(
                        "${{ env.PPATH }}",
                        "${{ env.TARGD }}"
                        )
                      );'

      # Deployment
      - name: No Jekyll
        run: touch ${{ env.SITED }}/__site/.nojekyll
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-ttfx
          FOLDER: ${{ env.SITED }}/__site
          TARGET-FOLDER: "${{ env.TARGD }}"
